#!/usr/bin/env bash
# Copyright (c) 2020 Matt Windsor and contributors
#
# This file is part of c4-scripts.
# Licenced under the MIT licence; see `LICENSE`.

# Adapts a bisection script to a form that `act-fuzz bisect` can understand.

# TODO(@MattWindsor91): make this parametric and more robust.
set -euo pipefail

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
readonly SCRIPTDIR

if [[ $# -lt 3 ]]; then
    echo "usage: $0 TRACE ORIGINAL SCRIPT [ARGS...]" >&2
    exit 2
fi

trace="$1"
original="$2"
script="$3"

shift 3

# TODO(@MattWindsor91): this is working around a failure in the litmusifying process when a litmus file has a name
# of the form foo.bar.baz (the output C file becomes foo.c).
OUTPUT_DIR="$(mktemp -d)" || exit 2
trap 'rm -rf ${OUTPUT_DIR}' EXIT

act-fuzz replay -trace "${trace}" "${original}" -o "${OUTPUT_DIR}/in.litmus"

"${script}" "$@" "${OUTPUT_DIR}/in.litmus"
